# Generated by Django 4.0.4 on 2022-06-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_documentrulevalue_review_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='rule_unit',
            field=models.CharField(choices=[('REVIEW', '심사'), ('DOCUMENT', '서류')], default='REVIEW', max_length=10),
        ),
    ]
