# Generated by Django 4.0.4 on 2022-06-24 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_documentruleresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRuleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('SUCCESS', '성공'), ('FAILURE', '실패')], default='FAILURE', max_length=10)),
                ('message', models.TextField(null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.contract')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.rule')),
            ],
        ),
    ]
