# Generated by Django 4.0.4 on 2022-06-24 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0007_reviewrule_reviewrulevalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentextractresult',
            name='review_document',
        ),
        migrations.AddField(
            model_name='documentextractresult',
            name='review',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='console.review'),
            preserve_default=False,
        ),
    ]
