# Generated by Django 4.0.4 on 2022-06-24 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0008_remove_documentextractresult_review_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrulevalue',
            name='review_rule',
        ),
        migrations.AddField(
            model_name='reviewrulevalue',
            name='review',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='console.review'),
            preserve_default=False,
        ),
    ]
